### ISSUE TITLE
Cannot open pcb file with Kicad 4.6

### ISSUE THREAD

**Issue by bogyxp** [hzeller/tmc2660-breakout#3]
I get an error while trying to open the pcb with Kicad 4.06.
Sais that the version the pcb was created with is newer than the one i have (which is actually the latest)
_Error loading board.
KiCad was unable to open this file, as it was created with a more recent version than the one you are running. To open it, you'll need to upgrade KiCad to a more recent version._
So i modified the first line of the pcb file and then i get an error: _PARSE ERROR: expecting learance,trace_width,(...) in input/source (...)_

**Comment by Duckle29** [comment]
Get the nightly builds. Not even just to open this, but because they are much nicer :)

**Comment by hzeller** [comment]
I just tested with the now current stable version 4.0.7, that is able to open it @bogyxp .

Also, you might be interested in https://github.com/hzeller/quadrigotion which is essentially my follow-up project. But it is 4 layer, while this project here only needs two layers.
(But that requires a nightly KiCAD build as I already have converted it to the upcoming 5.0 version of KiCAD)

**Comment by nadavmatalon** [comment]
Hi hzeller, 
I have version Kicad 4.0.7 installed but getting exactly the same error message as bogyxp above when trying to open the pcb design.
Any suggestion how to sort it out? (I'm a complete newbie to Kicad :-)

**Comment by hzeller** [comment]
So the board was done with Kicad that I compiled on 2016-01-05, whatever version that was around there. 

I can it open with a current 5.0.0 KiCAD as well, so maybe you should just get the current one.

**Comment by nadavmatalon** [comment]
Thanks for getting back to me.

Where did you get 5.0.0 from? All I see is the 4.0.7 version on the [official website](http://kicad-pcb.org/download/osx/)

Also, are you using Windows or MacOS? (I'm using the latter so maybe that's the problem)

**Comment by nadavmatalon** [comment]
Btw, forgot to mention, it makes little sense that something compiled in 2016 won't open on Kicad versions that came out much later (be it 4.0.7 or 5.0.0).

Any chance you might be able to upload the most minimal version of the schematics & board layout without all the extras and perhaps that will open correctly? (sorry, not sure what the correct terms are in Kicad for this but hopefully you get what I mean :-)

**Comment by hzeller** [comment]
I am using Linux and I just compiled it from source.
There are no extras, this is just the minimal version. Given that this is 2 years old, you might need to do a little adjustments with libraries.

**Comment by nadavmatalon** [comment]
Ok, thanks.

**Comment by nadavmatalon** [comment]
Sorry, one last question if I may: could you please tell me what were the dimensions of the vias you used for this board (drill size & overall diameter)?

**Comment by besi** [comment]
Since this is now two years old I would suggest to close the issue.

**Comment by hzeller** [comment]
Also, it should be fixed with https://github.com/hzeller/tmc2660-breakout/commit/c7a9a22456cac7ffe0ac24dff0842ad8f5f2ad77
